// Pays du monde (ISO 3166-1 alpha-2) : noms FR/EN, devise par défaut, région.
// Généré à partir de countries-list (devises, continents) et Intl (noms). Ordre : Afrique d'abord.
export type CountryRecord = { code: string; fr: string; en: string; cur: string | null; africa: boolean };

export const COUNTRIES: CountryRecord[] = [
  { code: "ZA", fr: "Afrique du Sud", en: "South Africa", cur: "ZAR", africa: true },
  { code: "DZ", fr: "Algérie", en: "Algeria", cur: "DZD", africa: true },
  { code: "AO", fr: "Angola", en: "Angola", cur: "AOA", africa: true },
  { code: "BJ", fr: "Bénin", en: "Benin", cur: "XOF", africa: true },
  { code: "BW", fr: "Botswana", en: "Botswana", cur: "BWP", africa: true },
  { code: "BF", fr: "Burkina Faso", en: "Burkina Faso", cur: "XOF", africa: true },
  { code: "BI", fr: "Burundi", en: "Burundi", cur: "BIF", africa: true },
  { code: "CM", fr: "Cameroun", en: "Cameroon", cur: "XAF", africa: true },
  { code: "CV", fr: "Cap-Vert", en: "Cape Verde", cur: "CVE", africa: true },
  { code: "KM", fr: "Comores", en: "Comoros", cur: "KMF", africa: true },
  { code: "CG", fr: "Congo-Brazzaville", en: "Congo - Brazzaville", cur: "XAF", africa: true },
  { code: "CD", fr: "Congo-Kinshasa", en: "Congo - Kinshasa", cur: "CDF", africa: true },
  { code: "CI", fr: "Côte d’Ivoire", en: "Côte d’Ivoire", cur: "XOF", africa: true },
  { code: "DJ", fr: "Djibouti", en: "Djibouti", cur: "DJF", africa: true },
  { code: "EG", fr: "Égypte", en: "Egypt", cur: "EGP", africa: true },
  { code: "ER", fr: "Érythrée", en: "Eritrea", cur: "ERN", africa: true },
  { code: "SZ", fr: "Eswatini", en: "Eswatini", cur: "SZL", africa: true },
  { code: "ET", fr: "Éthiopie", en: "Ethiopia", cur: "ETB", africa: true },
  { code: "GA", fr: "Gabon", en: "Gabon", cur: "XAF", africa: true },
  { code: "GM", fr: "Gambie", en: "Gambia", cur: "GMD", africa: true },
  { code: "GH", fr: "Ghana", en: "Ghana", cur: "GHS", africa: true },
  { code: "GN", fr: "Guinée", en: "Guinea", cur: "GNF", africa: true },
  { code: "GQ", fr: "Guinée équatoriale", en: "Equatorial Guinea", cur: "XAF", africa: true },
  { code: "GW", fr: "Guinée-Bissau", en: "Guinea-Bissau", cur: "XOF", africa: true },
  { code: "AC", fr: "Île de l’Ascension", en: "Ascension Island", cur: "SHP", africa: true },
  { code: "KE", fr: "Kenya", en: "Kenya", cur: "KES", africa: true },
  { code: "RE", fr: "La Réunion", en: "Réunion", cur: "EUR", africa: true },
  { code: "LS", fr: "Lesotho", en: "Lesotho", cur: "LSL", africa: true },
  { code: "LR", fr: "Liberia", en: "Liberia", cur: "LRD", africa: true },
  { code: "LY", fr: "Libye", en: "Libya", cur: "LYD", africa: true },
  { code: "MG", fr: "Madagascar", en: "Madagascar", cur: "MGA", africa: true },
  { code: "MW", fr: "Malawi", en: "Malawi", cur: "MWK", africa: true },
  { code: "ML", fr: "Mali", en: "Mali", cur: "XOF", africa: true },
  { code: "MA", fr: "Maroc", en: "Morocco", cur: "MAD", africa: true },
  { code: "MU", fr: "Maurice", en: "Mauritius", cur: "MUR", africa: true },
  { code: "MR", fr: "Mauritanie", en: "Mauritania", cur: "MRU", africa: true },
  { code: "YT", fr: "Mayotte", en: "Mayotte", cur: "EUR", africa: true },
  { code: "MZ", fr: "Mozambique", en: "Mozambique", cur: "MZN", africa: true },
  { code: "NA", fr: "Namibie", en: "Namibia", cur: "NAD", africa: true },
  { code: "NE", fr: "Niger", en: "Niger", cur: "XOF", africa: true },
  { code: "NG", fr: "Nigeria", en: "Nigeria", cur: "NGN", africa: true },
  { code: "UG", fr: "Ouganda", en: "Uganda", cur: "UGX", africa: true },
  { code: "CF", fr: "République centrafricaine", en: "Central African Republic", cur: "XAF", africa: true },
  { code: "RW", fr: "Rwanda", en: "Rwanda", cur: "RWF", africa: true },
  { code: "EH", fr: "Sahara occidental", en: "Western Sahara", cur: "MAD", africa: true },
  { code: "SH", fr: "Sainte-Hélène", en: "St. Helena", cur: "SHP", africa: true },
  { code: "ST", fr: "Sao Tomé-et-Principe", en: "São Tomé & Príncipe", cur: "STN", africa: true },
  { code: "SN", fr: "Sénégal", en: "Senegal", cur: "XOF", africa: true },
  { code: "SC", fr: "Seychelles", en: "Seychelles", cur: "SCR", africa: true },
  { code: "SL", fr: "Sierra Leone", en: "Sierra Leone", cur: "SLE", africa: true },
  { code: "SO", fr: "Somalie", en: "Somalia", cur: "SOS", africa: true },
  { code: "SD", fr: "Soudan", en: "Sudan", cur: "SDG", africa: true },
  { code: "SS", fr: "Soudan du Sud", en: "South Sudan", cur: "SSP", africa: true },
  { code: "TZ", fr: "Tanzanie", en: "Tanzania", cur: "TZS", africa: true },
  { code: "TD", fr: "Tchad", en: "Chad", cur: "XAF", africa: true },
  { code: "TG", fr: "Togo", en: "Togo", cur: "XOF", africa: true },
  { code: "TA", fr: "Tristan da Cunha", en: "Tristan da Cunha", cur: "SHP", africa: true },
  { code: "TN", fr: "Tunisie", en: "Tunisia", cur: "TND", africa: true },
  { code: "ZM", fr: "Zambie", en: "Zambia", cur: "ZMW", africa: true },
  { code: "ZW", fr: "Zimbabwe", en: "Zimbabwe", cur: "ZWG", africa: true },
  { code: "AF", fr: "Afghanistan", en: "Afghanistan", cur: "AFN", africa: false },
  { code: "AL", fr: "Albanie", en: "Albania", cur: "ALL", africa: false },
  { code: "DE", fr: "Allemagne", en: "Germany", cur: "EUR", africa: false },
  { code: "AD", fr: "Andorre", en: "Andorra", cur: "EUR", africa: false },
  { code: "AI", fr: "Anguilla", en: "Anguilla", cur: "XCD", africa: false },
  { code: "AQ", fr: "Antarctique", en: "Antarctica", cur: null, africa: false },
  { code: "AG", fr: "Antigua-et-Barbuda", en: "Antigua & Barbuda", cur: "XCD", africa: false },
  { code: "SA", fr: "Arabie saoudite", en: "Saudi Arabia", cur: "SAR", africa: false },
  { code: "AR", fr: "Argentine", en: "Argentina", cur: "ARS", africa: false },
  { code: "AM", fr: "Arménie", en: "Armenia", cur: "AMD", africa: false },
  { code: "AW", fr: "Aruba", en: "Aruba", cur: "AWG", africa: false },
  { code: "AU", fr: "Australie", en: "Australia", cur: "AUD", africa: false },
  { code: "AT", fr: "Autriche", en: "Austria", cur: "EUR", africa: false },
  { code: "AZ", fr: "Azerbaïdjan", en: "Azerbaijan", cur: "AZN", africa: false },
  { code: "BS", fr: "Bahamas", en: "Bahamas", cur: "BSD", africa: false },
  { code: "BH", fr: "Bahreïn", en: "Bahrain", cur: "BHD", africa: false },
  { code: "BD", fr: "Bangladesh", en: "Bangladesh", cur: "BDT", africa: false },
  { code: "BB", fr: "Barbade", en: "Barbados", cur: "BBD", africa: false },
  { code: "BE", fr: "Belgique", en: "Belgium", cur: "EUR", africa: false },
  { code: "BZ", fr: "Belize", en: "Belize", cur: "BZD", africa: false },
  { code: "BM", fr: "Bermudes", en: "Bermuda", cur: "BMD", africa: false },
  { code: "BT", fr: "Bhoutan", en: "Bhutan", cur: "BTN", africa: false },
  { code: "BY", fr: "Biélorussie", en: "Belarus", cur: "BYN", africa: false },
  { code: "BO", fr: "Bolivie", en: "Bolivia", cur: "BOB", africa: false },
  { code: "BA", fr: "Bosnie-Herzégovine", en: "Bosnia & Herzegovina", cur: "BAM", africa: false },
  { code: "BR", fr: "Brésil", en: "Brazil", cur: "BRL", africa: false },
  { code: "BN", fr: "Brunei", en: "Brunei", cur: "BND", africa: false },
  { code: "BG", fr: "Bulgarie", en: "Bulgaria", cur: "EUR", africa: false },
  { code: "KH", fr: "Cambodge", en: "Cambodia", cur: "KHR", africa: false },
  { code: "CA", fr: "Canada", en: "Canada", cur: "CAD", africa: false },
  { code: "CL", fr: "Chili", en: "Chile", cur: "CLP", africa: false },
  { code: "CN", fr: "Chine", en: "China", cur: "CNY", africa: false },
  { code: "CY", fr: "Chypre", en: "Cyprus", cur: "EUR", africa: false },
  { code: "CO", fr: "Colombie", en: "Colombia", cur: "COP", africa: false },
  { code: "KP", fr: "Corée du Nord", en: "North Korea", cur: "KPW", africa: false },
  { code: "KR", fr: "Corée du Sud", en: "South Korea", cur: "KRW", africa: false },
  { code: "CR", fr: "Costa Rica", en: "Costa Rica", cur: "CRC", africa: false },
  { code: "HR", fr: "Croatie", en: "Croatia", cur: "EUR", africa: false },
  { code: "CU", fr: "Cuba", en: "Cuba", cur: "CUP", africa: false },
  { code: "CW", fr: "Curaçao", en: "Curaçao", cur: "XCG", africa: false },
  { code: "DK", fr: "Danemark", en: "Denmark", cur: "DKK", africa: false },
  { code: "DM", fr: "Dominique", en: "Dominica", cur: "XCD", africa: false },
  { code: "AE", fr: "Émirats arabes unis", en: "United Arab Emirates", cur: "AED", africa: false },
  { code: "EC", fr: "Équateur", en: "Ecuador", cur: "USD", africa: false },
  { code: "ES", fr: "Espagne", en: "Spain", cur: "EUR", africa: false },
  { code: "EE", fr: "Estonie", en: "Estonia", cur: "EUR", africa: false },
  { code: "VA", fr: "État de la Cité du Vatican", en: "Vatican City", cur: "EUR", africa: false },
  { code: "US", fr: "États-Unis", en: "United States", cur: "USD", africa: false },
  { code: "FJ", fr: "Fidji", en: "Fiji", cur: "FJD", africa: false },
  { code: "FI", fr: "Finlande", en: "Finland", cur: "EUR", africa: false },
  { code: "FR", fr: "France", en: "France", cur: "EUR", africa: false },
  { code: "GE", fr: "Géorgie", en: "Georgia", cur: "GEL", africa: false },
  { code: "GS", fr: "Géorgie du Sud-et-les Îles Sandwich du Sud", en: "South Georgia & South Sandwich Islands", cur: "GBP", africa: false },
  { code: "GI", fr: "Gibraltar", en: "Gibraltar", cur: "GIP", africa: false },
  { code: "GR", fr: "Grèce", en: "Greece", cur: "EUR", africa: false },
  { code: "GD", fr: "Grenade", en: "Grenada", cur: "XCD", africa: false },
  { code: "GL", fr: "Groenland", en: "Greenland", cur: "DKK", africa: false },
  { code: "GP", fr: "Guadeloupe", en: "Guadeloupe", cur: "EUR", africa: false },
  { code: "GU", fr: "Guam", en: "Guam", cur: "USD", africa: false },
  { code: "GT", fr: "Guatemala", en: "Guatemala", cur: "GTQ", africa: false },
  { code: "GG", fr: "Guernesey", en: "Guernsey", cur: "GBP", africa: false },
  { code: "GY", fr: "Guyana", en: "Guyana", cur: "GYD", africa: false },
  { code: "GF", fr: "Guyane française", en: "French Guiana", cur: "EUR", africa: false },
  { code: "HT", fr: "Haïti", en: "Haiti", cur: "HTG", africa: false },
  { code: "HN", fr: "Honduras", en: "Honduras", cur: "HNL", africa: false },
  { code: "HU", fr: "Hongrie", en: "Hungary", cur: "HUF", africa: false },
  { code: "BV", fr: "Île Bouvet", en: "Bouvet Island", cur: "NOK", africa: false },
  { code: "CX", fr: "Île Christmas", en: "Christmas Island", cur: "AUD", africa: false },
  { code: "IM", fr: "Île de Man", en: "Isle of Man", cur: "GBP", africa: false },
  { code: "NF", fr: "Île Norfolk", en: "Norfolk Island", cur: "AUD", africa: false },
  { code: "AX", fr: "Îles Åland", en: "Åland Islands", cur: "EUR", africa: false },
  { code: "KY", fr: "Îles Caïmans", en: "Cayman Islands", cur: "KYD", africa: false },
  { code: "CC", fr: "Îles Cocos", en: "Cocos (Keeling) Islands", cur: "AUD", africa: false },
  { code: "CK", fr: "Îles Cook", en: "Cook Islands", cur: "NZD", africa: false },
  { code: "FO", fr: "Îles Féroé", en: "Faroe Islands", cur: "DKK", africa: false },
  { code: "HM", fr: "Îles Heard-et-MacDonald", en: "Heard & McDonald Islands", cur: "AUD", africa: false },
  { code: "FK", fr: "Îles Malouines", en: "Falkland Islands", cur: "FKP", africa: false },
  { code: "MP", fr: "Îles Mariannes du Nord", en: "Northern Mariana Islands", cur: "USD", africa: false },
  { code: "MH", fr: "Îles Marshall", en: "Marshall Islands", cur: "USD", africa: false },
  { code: "UM", fr: "Îles mineures éloignées des États-Unis", en: "U.S. Outlying Islands", cur: "USD", africa: false },
  { code: "PN", fr: "Îles Pitcairn", en: "Pitcairn Islands", cur: "NZD", africa: false },
  { code: "SB", fr: "Îles Salomon", en: "Solomon Islands", cur: "SBD", africa: false },
  { code: "TC", fr: "Îles Turques-et-Caïques", en: "Turks & Caicos Islands", cur: "USD", africa: false },
  { code: "VG", fr: "Îles Vierges britanniques", en: "British Virgin Islands", cur: "USD", africa: false },
  { code: "VI", fr: "Îles Vierges des États-Unis", en: "U.S. Virgin Islands", cur: "USD", africa: false },
  { code: "IN", fr: "Inde", en: "India", cur: "INR", africa: false },
  { code: "ID", fr: "Indonésie", en: "Indonesia", cur: "IDR", africa: false },
  { code: "IQ", fr: "Irak", en: "Iraq", cur: "IQD", africa: false },
  { code: "IR", fr: "Iran", en: "Iran", cur: "IRR", africa: false },
  { code: "IE", fr: "Irlande", en: "Ireland", cur: "EUR", africa: false },
  { code: "IS", fr: "Islande", en: "Iceland", cur: "ISK", africa: false },
  { code: "IL", fr: "Israël", en: "Israel", cur: "ILS", africa: false },
  { code: "IT", fr: "Italie", en: "Italy", cur: "EUR", africa: false },
  { code: "JM", fr: "Jamaïque", en: "Jamaica", cur: "JMD", africa: false },
  { code: "JP", fr: "Japon", en: "Japan", cur: "JPY", africa: false },
  { code: "JE", fr: "Jersey", en: "Jersey", cur: "GBP", africa: false },
  { code: "JO", fr: "Jordanie", en: "Jordan", cur: "JOD", africa: false },
  { code: "KZ", fr: "Kazakhstan", en: "Kazakhstan", cur: "KZT", africa: false },
  { code: "KG", fr: "Kirghizstan", en: "Kyrgyzstan", cur: "KGS", africa: false },
  { code: "KI", fr: "Kiribati", en: "Kiribati", cur: "AUD", africa: false },
  { code: "XK", fr: "Kosovo", en: "Kosovo", cur: "EUR", africa: false },
  { code: "KW", fr: "Koweït", en: "Kuwait", cur: "KWD", africa: false },
  { code: "LA", fr: "Laos", en: "Laos", cur: "LAK", africa: false },
  { code: "LV", fr: "Lettonie", en: "Latvia", cur: "EUR", africa: false },
  { code: "LB", fr: "Liban", en: "Lebanon", cur: "LBP", africa: false },
  { code: "LI", fr: "Liechtenstein", en: "Liechtenstein", cur: "CHF", africa: false },
  { code: "LT", fr: "Lituanie", en: "Lithuania", cur: "EUR", africa: false },
  { code: "LU", fr: "Luxembourg", en: "Luxembourg", cur: "EUR", africa: false },
  { code: "MK", fr: "Macédoine du Nord", en: "North Macedonia", cur: "MKD", africa: false },
  { code: "MY", fr: "Malaisie", en: "Malaysia", cur: "MYR", africa: false },
  { code: "MV", fr: "Maldives", en: "Maldives", cur: "MVR", africa: false },
  { code: "MT", fr: "Malte", en: "Malta", cur: "EUR", africa: false },
  { code: "MQ", fr: "Martinique", en: "Martinique", cur: "EUR", africa: false },
  { code: "MX", fr: "Mexique", en: "Mexico", cur: "MXN", africa: false },
  { code: "FM", fr: "Micronésie", en: "Micronesia", cur: "USD", africa: false },
  { code: "MD", fr: "Moldavie", en: "Moldova", cur: "MDL", africa: false },
  { code: "MC", fr: "Monaco", en: "Monaco", cur: "EUR", africa: false },
  { code: "MN", fr: "Mongolie", en: "Mongolia", cur: "MNT", africa: false },
  { code: "ME", fr: "Monténégro", en: "Montenegro", cur: "EUR", africa: false },
  { code: "MS", fr: "Montserrat", en: "Montserrat", cur: "XCD", africa: false },
  { code: "MM", fr: "Myanmar (Birmanie)", en: "Myanmar (Burma)", cur: "MMK", africa: false },
  { code: "NR", fr: "Nauru", en: "Nauru", cur: "AUD", africa: false },
  { code: "NP", fr: "Népal", en: "Nepal", cur: "NPR", africa: false },
  { code: "NI", fr: "Nicaragua", en: "Nicaragua", cur: "NIO", africa: false },
  { code: "NU", fr: "Niue", en: "Niue", cur: "NZD", africa: false },
  { code: "NO", fr: "Norvège", en: "Norway", cur: "NOK", africa: false },
  { code: "NC", fr: "Nouvelle-Calédonie", en: "New Caledonia", cur: "XPF", africa: false },
  { code: "NZ", fr: "Nouvelle-Zélande", en: "New Zealand", cur: "NZD", africa: false },
  { code: "OM", fr: "Oman", en: "Oman", cur: "OMR", africa: false },
  { code: "UZ", fr: "Ouzbékistan", en: "Uzbekistan", cur: "UZS", africa: false },
  { code: "PK", fr: "Pakistan", en: "Pakistan", cur: "PKR", africa: false },
  { code: "PW", fr: "Palaos", en: "Palau", cur: "USD", africa: false },
  { code: "PA", fr: "Panama", en: "Panama", cur: "PAB", africa: false },
  { code: "PG", fr: "Papouasie-Nouvelle-Guinée", en: "Papua New Guinea", cur: "PGK", africa: false },
  { code: "PY", fr: "Paraguay", en: "Paraguay", cur: "PYG", africa: false },
  { code: "NL", fr: "Pays-Bas", en: "Netherlands", cur: "EUR", africa: false },
  { code: "BQ", fr: "Pays-Bas caribéens", en: "Caribbean Netherlands", cur: "USD", africa: false },
  { code: "PE", fr: "Pérou", en: "Peru", cur: "PEN", africa: false },
  { code: "PH", fr: "Philippines", en: "Philippines", cur: "PHP", africa: false },
  { code: "PL", fr: "Pologne", en: "Poland", cur: "PLN", africa: false },
  { code: "PF", fr: "Polynésie française", en: "French Polynesia", cur: "XPF", africa: false },
  { code: "PR", fr: "Porto Rico", en: "Puerto Rico", cur: "USD", africa: false },
  { code: "PT", fr: "Portugal", en: "Portugal", cur: "EUR", africa: false },
  { code: "QA", fr: "Qatar", en: "Qatar", cur: "QAR", africa: false },
  { code: "HK", fr: "R.A.S. chinoise de Hong Kong", en: "Hong Kong SAR China", cur: "HKD", africa: false },
  { code: "MO", fr: "R.A.S. chinoise de Macao", en: "Macao SAR China", cur: "MOP", africa: false },
  { code: "DO", fr: "République dominicaine", en: "Dominican Republic", cur: "DOP", africa: false },
  { code: "RO", fr: "Roumanie", en: "Romania", cur: "RON", africa: false },
  { code: "GB", fr: "Royaume-Uni", en: "United Kingdom", cur: "GBP", africa: false },
  { code: "RU", fr: "Russie", en: "Russia", cur: "RUB", africa: false },
  { code: "BL", fr: "Saint-Barthélemy", en: "St. Barthélemy", cur: "EUR", africa: false },
  { code: "KN", fr: "Saint-Christophe-et-Niévès", en: "St. Kitts & Nevis", cur: "XCD", africa: false },
  { code: "SM", fr: "Saint-Marin", en: "San Marino", cur: "EUR", africa: false },
  { code: "MF", fr: "Saint-Martin", en: "St. Martin", cur: "EUR", africa: false },
  { code: "SX", fr: "Saint-Martin (partie néerlandaise)", en: "Sint Maarten", cur: "XCG", africa: false },
  { code: "PM", fr: "Saint-Pierre-et-Miquelon", en: "St. Pierre & Miquelon", cur: "EUR", africa: false },
  { code: "VC", fr: "Saint-Vincent-et-les Grenadines", en: "St. Vincent & Grenadines", cur: "XCD", africa: false },
  { code: "LC", fr: "Sainte-Lucie", en: "St. Lucia", cur: "XCD", africa: false },
  { code: "SV", fr: "Salvador", en: "El Salvador", cur: "USD", africa: false },
  { code: "WS", fr: "Samoa", en: "Samoa", cur: "WST", africa: false },
  { code: "AS", fr: "Samoa américaines", en: "American Samoa", cur: "USD", africa: false },
  { code: "RS", fr: "Serbie", en: "Serbia", cur: "RSD", africa: false },
  { code: "SG", fr: "Singapour", en: "Singapore", cur: "SGD", africa: false },
  { code: "SK", fr: "Slovaquie", en: "Slovakia", cur: "EUR", africa: false },
  { code: "SI", fr: "Slovénie", en: "Slovenia", cur: "EUR", africa: false },
  { code: "LK", fr: "Sri Lanka", en: "Sri Lanka", cur: "LKR", africa: false },
  { code: "SE", fr: "Suède", en: "Sweden", cur: "SEK", africa: false },
  { code: "CH", fr: "Suisse", en: "Switzerland", cur: "CHF", africa: false },
  { code: "SR", fr: "Suriname", en: "Suriname", cur: "SRD", africa: false },
  { code: "SJ", fr: "Svalbard et Jan Mayen", en: "Svalbard & Jan Mayen", cur: "NOK", africa: false },
  { code: "SY", fr: "Syrie", en: "Syria", cur: "SYP", africa: false },
  { code: "TJ", fr: "Tadjikistan", en: "Tajikistan", cur: "TJS", africa: false },
  { code: "TW", fr: "Taïwan", en: "Taiwan", cur: "TWD", africa: false },
  { code: "CZ", fr: "Tchéquie", en: "Czechia", cur: "CZK", africa: false },
  { code: "TF", fr: "Terres australes françaises", en: "French Southern Territories", cur: "EUR", africa: false },
  { code: "IO", fr: "Territoire britannique de l’océan Indien", en: "British Indian Ocean Territory", cur: "USD", africa: false },
  { code: "PS", fr: "Territoires palestiniens", en: "Palestinian Territories", cur: "ILS", africa: false },
  { code: "TH", fr: "Thaïlande", en: "Thailand", cur: "THB", africa: false },
  { code: "TL", fr: "Timor oriental", en: "Timor-Leste", cur: "USD", africa: false },
  { code: "TK", fr: "Tokelau", en: "Tokelau", cur: "NZD", africa: false },
  { code: "TO", fr: "Tonga", en: "Tonga", cur: "TOP", africa: false },
  { code: "TT", fr: "Trinité-et-Tobago", en: "Trinidad & Tobago", cur: "TTD", africa: false },
  { code: "TM", fr: "Turkménistan", en: "Turkmenistan", cur: "TMT", africa: false },
  { code: "TR", fr: "Turquie", en: "Türkiye", cur: "TRY", africa: false },
  { code: "TV", fr: "Tuvalu", en: "Tuvalu", cur: "AUD", africa: false },
  { code: "UA", fr: "Ukraine", en: "Ukraine", cur: "UAH", africa: false },
  { code: "UY", fr: "Uruguay", en: "Uruguay", cur: "UYU", africa: false },
  { code: "VU", fr: "Vanuatu", en: "Vanuatu", cur: "VUV", africa: false },
  { code: "VE", fr: "Venezuela", en: "Venezuela", cur: "VES", africa: false },
  { code: "VN", fr: "Viêt Nam", en: "Vietnam", cur: "VND", africa: false },
  { code: "WF", fr: "Wallis-et-Futuna", en: "Wallis & Futuna", cur: "XPF", africa: false },
  { code: "YE", fr: "Yémen", en: "Yemen", cur: "YER", africa: false },
];
