-- Étape 3 : notifications push / appareils + nouveaux événements de notification.
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FOLLOW';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PURCHASE_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CALL_INCOMING';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CALL_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CALL_MISSED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CALL_ENDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LIVE_STARTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GIFT_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TIP_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REFUND';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WITHDRAWAL';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MODERATION';

CREATE TABLE "PushDevice" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "platform" VARCHAR(10) NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PushDevice_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "PushDevice_token_key" ON "PushDevice"("token");
CREATE INDEX "PushDevice_userId_active_idx" ON "PushDevice"("userId", "active");
ALTER TABLE "PushDevice" ADD CONSTRAINT "PushDevice_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
