export type ConfigDefault = {
  key: string;
  value: unknown;
  type: 'STRING' | 'INTEGER' | 'DECIMAL' | 'BOOLEAN' | 'JSON';
  category: 'PREMIUM' | 'COMMISSION' | 'CREATOR_POOL' | 'MONETIZATION' | 'SHORTS' | 'VIDEOS' | 'LIVES' | 'WITHDRAWALS' | 'FEATURE_PRICING' | 'ADVERTISING' | 'PROMOTIONS' | 'GENERAL';
  description: string;
};

export const CONFIG_DEFAULTS: ConfigDefault[] = [
  { key: 'PREMIUM.MONTHLY_PRICE', value: 9500, type: 'INTEGER', category: 'PREMIUM', description: 'Prix mensuel Face to Face Premium.' },
  { key: 'PREMIUM.ANNUAL_PRICE', value: 95000, type: 'INTEGER', category: 'PREMIUM', description: 'Prix annuel Face to Face Premium.' },
  { key: 'PREMIUM.TRIAL_ENABLED', value: true, type: 'BOOLEAN', category: 'PREMIUM', description: 'Active ou désactive l’essai Premium.' },
  { key: 'PREMIUM.TRIAL_DAYS', value: 7, type: 'INTEGER', category: 'PREMIUM', description: 'Durée de l’essai Premium en jours.' },
  { key: 'COMMISSION.PLATFORM_PERCENT', value: 20, type: 'DECIMAL', category: 'COMMISSION', description: 'Part de la plateforme sur les paiements directs.' },
  { key: 'COMMISSION.CREATOR_PERCENT', value: 80, type: 'DECIMAL', category: 'COMMISSION', description: 'Part créateur sur les paiements directs.' },
  { key: 'CREATOR_POOL.PLATFORM_PERCENT', value: 60, type: 'DECIMAL', category: 'CREATOR_POOL', description: 'Part plateforme des revenus publicitaires destinée au modèle de pool.' },
  { key: 'CREATOR_POOL.CREATOR_PERCENT', value: 40, type: 'DECIMAL', category: 'CREATOR_POOL', description: 'Part des revenus publicitaires affectée au Creator Pool.' },
  { key: 'MONETIZATION.MIN_SUBSCRIBERS', value: 500, type: 'INTEGER', category: 'MONETIZATION', description: 'Nombre minimum d’abonnés pour la monétisation.' },
  { key: 'MONETIZATION.MIN_WATCH_HOURS', value: 3000, type: 'INTEGER', category: 'MONETIZATION', description: 'Heures de visionnage minimum sur la période configurée.' },
  { key: 'MONETIZATION.WATCH_PERIOD_DAYS', value: 365, type: 'INTEGER', category: 'MONETIZATION', description: 'Période de calcul des heures de visionnage.' },
  { key: 'MONETIZATION.MIN_PUBLICATIONS', value: 3, type: 'INTEGER', category: 'MONETIZATION', description: 'Nombre minimum de publications.' },
  { key: 'MONETIZATION.PUBLICATIONS_PERIOD_DAYS', value: 90, type: 'INTEGER', category: 'MONETIZATION', description: 'Période de calcul des publications.' },
  { key: 'MONETIZATION.MIN_PAYMENT_AGE', value: 18, type: 'INTEGER', category: 'MONETIZATION', description: 'Âge minimum pour recevoir des paiements.' },
  { key: 'MONETIZATION.MIN_WATCH_TIME_SECONDS', value: 3000 * 60 * 60, type: 'INTEGER', category: 'MONETIZATION', description: 'Temps de visionnage minimum des vidéos longues.' },
  { key: 'MONETIZATION.MIN_SHORT_VIEWS', value: 3000000, type: 'INTEGER', category: 'MONETIZATION', description: 'Vues Shorts minimum pour la monétisation.' },
  { key: 'SHORTS.WATCH_PERIOD_DAYS', value: 90, type: 'INTEGER', category: 'SHORTS', description: 'Période de calcul des vues Shorts.' },
  { key: 'SHORTS.MIN_WATCHED_SECONDS', value: 0, type: 'INTEGER', category: 'SHORTS', description: 'Durée minimale regardée pour une vue qualifiée Short.' },
  { key: 'SHORTS.MIN_WATCH_PERCENT_BPS', value: 0, type: 'INTEGER', category: 'SHORTS', description: 'Pourcentage minimal regardé pour une vue qualifiée Short.' },
  { key: 'VIDEOS.MIN_WATCHED_SECONDS', value: 0, type: 'INTEGER', category: 'VIDEOS', description: 'Durée minimale regardée pour une vue qualifiée vidéo.' },
  { key: 'VIDEOS.MIN_WATCH_PERCENT_BPS', value: 0, type: 'INTEGER', category: 'VIDEOS', description: 'Pourcentage minimal regardé pour une vue qualifiée vidéo.' },
  { key: 'MONETIZATION.REQUIRE_VERIFIED_ACCOUNT', value: true, type: 'BOOLEAN', category: 'MONETIZATION', description: 'Exige un compte vérifié.' },
  { key: 'MONETIZATION.REQUIRE_NO_ACTIVE_SANCTION', value: true, type: 'BOOLEAN', category: 'MONETIZATION', description: 'Exige l’absence de sanction active.' },
  { key: 'MONETIZATION.REQUIRE_ORIGINAL_CONTENT', value: true, type: 'BOOLEAN', category: 'MONETIZATION', description: 'Exige du contenu original.' },
  { key: 'MONETIZATION.REQUIRE_MANUAL_VALIDATION', value: true, type: 'BOOLEAN', category: 'MONETIZATION', description: 'Exige une validation manuelle de la monétisation.' },
  { key: 'MONETIZATION.EXCLUDE_ARTIFICIAL_VIEWS', value: true, type: 'BOOLEAN', category: 'MONETIZATION', description: 'Exclut les vues artificielles.' },
  { key: 'MONETIZATION.EXCLUDE_REMOVED_CONTENT', value: true, type: 'BOOLEAN', category: 'MONETIZATION', description: 'Exclut le contenu supprimé.' },
  { key: 'MONETIZATION.EXCLUDE_PRIVATE_CONTENT', value: true, type: 'BOOLEAN', category: 'MONETIZATION', description: 'Exclut le contenu privé.' },
  { key: 'SHORTS.MIN_VIEWS', value: 3000000, type: 'INTEGER', category: 'SHORTS', description: 'Vues Shorts minimum.' },
  { key: 'SHORTS.VIEWS_PERIOD_DAYS', value: 90, type: 'INTEGER', category: 'SHORTS', description: 'Période de calcul des vues Shorts.' },
  { key: 'SHORTS.MIN_DURATION_SECONDS', value: 1, type: 'INTEGER', category: 'SHORTS', description: 'Durée minimale d’un Short.' },
  { key: 'SHORTS.MIN_COMPLETION_PERCENT', value: 50, type: 'DECIMAL', category: 'SHORTS', description: 'Taux de complétion minimum pour une vue qualifiée.' },
  { key: 'SHORTS.CREATOR_POOL_PERCENT', value: 40, type: 'DECIMAL', category: 'SHORTS', description: 'Part du pool affectée aux Shorts.' },
  { key: 'VIDEOS.MIN_DURATION_SECONDS', value: 60, type: 'INTEGER', category: 'VIDEOS', description: 'Durée minimale d’une vidéo longue.' },
  { key: 'VIDEOS.MIN_WATCH_PERCENT', value: 30, type: 'DECIMAL', category: 'VIDEOS', description: 'Pourcentage minimum regardé pour une vue qualifiée.' },
  { key: 'VIDEOS.MIN_QUALIFIED_VIEWS', value: 1000, type: 'INTEGER', category: 'VIDEOS', description: 'Seuil indicatif de vues qualifiées.' },
  { key: 'LIVES.MIN_DURATION_MINUTES', value: 30, type: 'INTEGER', category: 'LIVES', description: 'Durée minimale d’un Live éligible.' },
  { key: 'LIVES.MIN_DURATION_SECONDS', value: 30 * 60, type: 'INTEGER', category: 'LIVES', description: 'Durée minimale d’un Live éligible, en secondes.' },
  { key: 'LIVES.MIN_VIEWERS', value: 10, type: 'INTEGER', category: 'LIVES', description: 'Nombre minimum de spectateurs.' },
  { key: 'LIVES.MIN_UNIQUE_VIEWERS', value: 10, type: 'INTEGER', category: 'LIVES', description: 'Nombre minimum de spectateurs uniques.' },
  { key: 'LIVES.MIN_WATCH_MINUTES', value: 100, type: 'INTEGER', category: 'LIVES', description: 'Temps de visionnage minimum.' },
  { key: 'LIVES.MIN_WATCH_TIME_SECONDS', value: 100 * 60, type: 'INTEGER', category: 'LIVES', description: 'Temps de visionnage minimum d’un Live.' },
  { key: 'LIVES.MIN_ENGAGEMENT_BPS', value: 0, type: 'INTEGER', category: 'LIVES', description: 'Engagement minimum d’un Live, en points de base.' },
  { key: 'WITHDRAWALS.MIN_AMOUNT', value: 10000, type: 'INTEGER', category: 'WITHDRAWALS', description: 'Montant minimum d’un retrait.' },
  { key: 'WITHDRAWALS.FEE', value: 0, type: 'INTEGER', category: 'WITHDRAWALS', description: 'Frais fixes de retrait.' },
  { key: 'WITHDRAWALS.MIN_DAYS_BETWEEN', value: 7, type: 'INTEGER', category: 'WITHDRAWALS', description: 'Délai minimum entre deux retraits.' },
  { key: 'WITHDRAWALS.REQUIRE_ADMIN_VALIDATION', value: true, type: 'BOOLEAN', category: 'WITHDRAWALS', description: 'Exige une validation administrative.' },
  { key: 'ADVERTISING.ENABLED', value: true, type: 'BOOLEAN', category: 'ADVERTISING', description: 'Active la publicité pour les utilisateurs non Premium.' },
  { key: 'ADVERTISING.MIN_SECONDS_BETWEEN', value: 120, type: 'INTEGER', category: 'ADVERTISING', description: 'Fréquence minimale entre insertions publicitaires.' },
  { key: 'ADVERTISING.CREATOR_SHARE_PERCENT', value: 40, type: 'DECIMAL', category: 'ADVERTISING', description: 'Part publicitaire attribuée aux créateurs.' },
  { key: 'FEATURE_PRICING.PAID_MESSAGE_MIN', value: 100, type: 'INTEGER', category: 'FEATURE_PRICING', description: 'Prix minimum d’un message payant.' },
  { key: 'FEATURE_PRICING.CUSTOM_VIDEO_MIN', value: 1000, type: 'INTEGER', category: 'FEATURE_PRICING', description: 'Prix minimum d’une vidéo personnalisée.' },
  { key: 'PROMOTIONS.ENABLED', value: true, type: 'BOOLEAN', category: 'PROMOTIONS', description: 'Active les promotions administratives.' },
  { key: 'COINS.COMMISSION_BPS', value: 2000, type: 'INTEGER', category: 'COMMISSION', description: 'Commission plateforme sur les cadeaux et pourboires en coins, en points de base (2000 = 20 %).' },
  { key: 'MESSAGING.VIEW_ONCE_ENABLED', value: true, type: 'BOOLEAN', category: 'GENERAL', description: 'Active ou désactive les messages à vue unique dans les conversations privées.' },
  { key: 'MESSAGING.VIEW_ONCE_PAID_ALLOWED', value: true, type: 'BOOLEAN', category: 'GENERAL', description: 'Autorise les photos et vidéos à vue unique payantes (même règle de prix et de commission que les messages payants).' },
  { key: 'GROUP_ACCESS.COMMISSION_BPS', value: 2000, type: 'INTEGER', category: 'COMMISSION', description: 'Commission plateforme sur l’accès payant aux groupes, en points de base (2000 = 20 %). Figée à chaque achat.' },
  { key: 'STORIES.ENABLED', value: true, type: 'BOOLEAN', category: 'GENERAL', description: 'Active ou désactive les stories (publication et affichage).' },
  { key: 'STORIES.DEFAULT_HOURS', value: 24, type: 'INTEGER', category: 'GENERAL', description: 'Durée de vie par défaut d’une story, en heures.' },
  { key: 'STORIES.MAX_HOURS', value: 72, type: 'INTEGER', category: 'GENERAL', description: 'Durée de vie maximale qu’un auteur peut choisir pour une story, en heures.' },
  { key: 'AUDIENCE.MIN_GROUP_SIZE', value: 5, type: 'INTEGER', category: 'GENERAL', description: 'Nombre minimum d’abonnés d’un pays pour qu’il apparaisse séparément dans l’audience du créateur ; en dessous, il est regroupé dans « Autres ».' },
  { key: 'DISPUTES.RESPONSE_DAYS', value: 3, type: 'INTEGER', category: 'GENERAL', description: 'Délai, en jours, pour répondre à un litige (appel ou vidéo personnalisée). Sans réponse à l’échéance, le litige se clôt sans montant.' },
  { key: 'CONTENT.PURGE_AFTER_DAYS', value: 30, type: 'INTEGER', category: 'GENERAL', description: 'Délai, en jours, entre le retrait d’un contenu et la purge définitive possible par le super administrateur.' },
];
